[package]
name = "quackdb-internal"
description = "Low level binding to libduckdb-sys"
version = "0.3.0"
edition = "2021"

authors = ["Rongcui Dong <rongcuid@outlook.com>"]
repository = "https://github/rongcuid/quackdb"
homepage = "https://github/rongcuid/quackdb"

license = "MIT"
keywords = ["duckdb", "database", "ffi"]
categories = ["database"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
paste = "1"

libduckdb-sys = { version = "0.9", features = ["bundled"] }

cstr = "0.2"
arrow = { version = "48", features = ["ffi"] }
time = "^0.3"
serde = "1"
serde_json = "1"
uuid = "1"
regex = "1"
rust_decimal = "1"
