[package]
name = "quackdb-internal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
strum = { version = "0.25", features = ["derive"] }
paste = "1"

libduckdb-sys = "0.9"

cstr = "0.2"
arrow = { version = "47", features = ["ffi"] }
# parquet = "46"
time = "^0.3"
serde = "1"
serde_json = "1"
uuid = "1"
regex = "1"
rust_decimal = "1"
