[package]
name = "quackdb-conversion"
version = "0.4.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quackdb-internal = { path = "../quackdb-internal", version = "0.4.0-dev" }

paste = "1"

time = "0.3"
